###########################################################
#                                                         #
# Copyright (c)                                           #
#                                                         #
# The Verifiable & Control-Theoretic Robotics (VECTR) Lab #
# University of California, Los Angeles                   #
#                                                         #
# Authors: Kenny J. Chen, Ryan Nemiroff, Brett T. Lopez   #
# Contact: {kennyjchen, ryguyn, btlopez}@ucla.edu         #
#                                                         #
###########################################################

/**:
  ros__parameters:

    version: 1.1.1

    adaptive: true

    adaptive/spaciousness/min: 0.25
    adaptive/spaciousness/max: 4.0
    adaptive/density/factor_min: 0.5
    adaptive/density/factor_max: 2.0

    pointcloud/deskew: true
    pointcloud/voxelize: true

    imu/calibration: true
    imu/intrinsics/accel/bias: [ 0.0, 0.0, 0.0 ]
    imu/intrinsics/accel/sm:   [ 1.,  0.,  0.,
                                 0.,  1.,  0.,
                                 0.,  0.,  1. ]
    imu/intrinsics/gyro/bias: [ 0.0, 0.0, 0.0 ]

    extrinsics/baselink2imu/t: [ 0.695184352554, -0.018795377723, 0.354195063558 ]
    extrinsics/baselink2imu/R: [ 0.999975570277, -0.004638447243, -0.005229116251,
                                -0.004619504871, -0.999982745999, 0.003628757219,
                                -0.005245857827, -0.003604512642, -0.999979744027 ]
    extrinsics/baselink2lidar/t: [ 0.684417099243, 0.003533413989, 0.321135016591 ]
    extrinsics/baselink2lidar/R: [ 0.999936353230, 0.009172616805, -0.006569063163,
                                   0.009196546763, -0.999951151377, 0.003621931511,
                                  -0.006535519683, -0.003682113683, -0.999971864115 ]
